@TmsApi_HostAddress = http://localhost:5000

GET {{TmsApi_HostAddress}}/weatherforecast/
Accept: application/json

###

GET {{TmsApi_HostAddress}}/api/assessments/results
Accept: application/json
###


GET {{TmsApi_HostAddress}}/api/enrollments/worker-smoke 
Accept: application/json
###
GET {{TmsApi_HostAddress}}/api/enrollments/
Accept: application/json
###
POST {{TmsApi_HostAddress}}/api/enrollments/
Content-Type: application/json
Accept: application/json

{
  "studentId": "S001",
  "courseCode": "CS101"
}
###
GET http://localhost:5000/api/enrollments/d7927a37
###
DELETE http://localhost:5000/api/enrollments/d7927a37
###
GET http://localhost:5000/api/error
###
GET http://localhost:5000/scalar
###
POST http://localhost:5000/api/students
Content-Type: application/json

{
  "name": "John",
  "gpa": 3.5
}
###
GET http://localhost:5000/api/students
###
GET http://localhost:5000/api/students/357b22ac
###
DELETE http://localhost:5000/api/students/357b22ac
###
POST http://localhost:5000/api/courses
Content-Type: application/json

{
  "code": "CS-101",
  "title": "Introduction to Programming",
  "capacity": 30
}
###
GET http://localhost:5000/api/courses
###
GET http://localhost:5000/api/courses/CS-101
###
DELETE http://localhost:5000/api/courses/CS-101
###
//GET http://localhost:5000/api/assessments

###
POST http://localhost:5000/api/assessments
Content-Type: application/json

{
    "studentId": "S001",
    "courseCode": "CS101",
    "score": 92
}
###
GET http://localhost:5000/api/assessments
###
GET http://localhost:5000/api/assessments/0e01c990

###
DELETE http://localhost:5000/api/assessments/0e01c990

###

GET http://localhost:5000/api/test/deferred
###
 GET http://localhost:5000/api/test/translation-fail
 ###
 GET http://localhost:5000/api/test/active-count 
 ###

